### ISSUE TITLE
train error, my cuda is 9.2

### ISSUE THREAD

**Issue by tsing-cv** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#8]
`Traceback (most recent call last):
  File "train.py", line 13, in <module>
    from libs.networks import build_whole_network
  File "../libs/networks/build_whole_network.py", line 13, in <module>
    from libs.box_utils import boxes_utils, iou_rotate
  File "../libs/box_utils/iou_rotate.py", line 10, in <module>
    from libs.box_utils.rbbox_overlaps import rbbx_overlaps
ImportError: ../libs/box_utils/rbbox_overlaps.cpython-36m-x86_64-linux-gnu.so: undefined symbol: __cudaPopCallConfiguration
`
@yangxue0827

**Comment by yangxue0827** [comment]
![image](https://user-images.githubusercontent.com/29257168/48113701-154b5e00-e297-11e8-8c13-5faa9e812500.png) @tsing-cv

**Comment by tsing-cv** [comment]
compiled this codes as your discribled

**Comment by yangxue0827** [comment]
Delete the .so and .cpp files and recompile them. @tsing-cv

**Comment by tsing-cv** [comment]
I deleted the .so and .cpp files,but still can not solve this problem

**Comment by tsing-cv** [comment]
@yangxue0827 @yangJirui I used python36, cuda 9 encountered ```python
no CUDA-capable device is detected, ```when i used python27, cuda 8 encountered ```python
undefined symbol: __cudaPopCallConfiguration
```

**Comment by yangxue0827** [comment]
Try to set value of GPU_GROUP in cfgs to choose your gpu index. Default is 2, you may dont have three gpus. @tsing-cv

**Comment by tsing-cv** [comment]
I seted GPU_GROUP="0";but still raise this 
`CUDA driver version is insufficient for CUDA runtime version`
Other projects without these problems.
The devices is: gpu 1080ti, cuda9.2 nvidia-driver 384 
@yangxue0827

**Comment by yangxue0827** [comment]
try CUDA_VISIBLE_DEVICES=0 python train.py @tsing-cv
