### ISSUE TITLE
OutOfRangeError in read_tfrecord.py

### ISSUE THREAD

**Issue by guoguangchao** [DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow#9]
I made a dataset myself, and generated tfrecord file in ../data/tfrecord, when i run trian.py, i got error.

tensorflow:1.2.0
python:2.7
cuda:8.0

the xml format is:
```
<?xml version='1.0' encoding='utf-8'?>
<annotation>
	<folder>VOC2007</folder>
	<filename>000001.jpg</filename>
	<path>E:\idcard0\000001.jpg</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>465</width>
		<height>394</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>name</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<x0>321</x0><y0>312</y0><x1>283</x1><y1>301</y1><x2>288</x2><y2>283</y2><x3>326</x3><y3>293</y3></bndbox>
	</object>
	<object>
		<name>address</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<x0>350</x0><y0>223</y0><x1>199</x1><y1>183</y1><x2>208</x2><y2>148</y2><x3>359</x3><y3>188</y3></bndbox>
	</object>
	<object>
		<name>id_num</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<x0>315</x0><y0>136</y0><x1>115</x1><y1>82</y1><x2>120</x2><y2>62</y2><x3>321</x3><y3>116</y3></bndbox>
	</object>
	<object>
		<name>head</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<x0>165</x0><y0>271</y0><x1>53</x1><y1>241</y1><x2>92</x2><y2>99</y2><x3>203</x3><y3>129</y3></bndbox>
	</object>
</annotation>
```

python convert_data_to_tfrecord.py --VOC_dir='/home/sigma/soft/learn/tensorflow-learn/RRPN_Faster-RCNN_Tensorflow-master/dataset/' --xml_dir='labels' --image_dir='images' --save_name='train' --img_format='.jpg' --dataset='idcard'
++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--
/home/sigma/soft/learn/tensorflow-learn/RRPN_Faster-RCNN_Tensorflow-master/data
Conversion progress:[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>]100%	3000/3000
Conversion is complete!

when i run trian.py i got the message:

++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--++--
/home/sigma/soft/learn/tensorflow-learn/RRPN_Faster-RCNN_Tensorflow-master
tfrecord path is --> /home/sigma/soft/learn/tensorflow-learn/RRPN_Faster-RCNN_Tensorflow-master/data/tfrecord/idcard_train*
WARNING:tensorflow:From train.py:63: get_regularization_losses (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.get_regularization_losses instead.
/home/sigma/.virtualenvs/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
checkpoint_path==None
model restore from pretrained mode, path is : /home/sigma/soft/learn/tensorflow-learn/RRPN_Faster-RCNN_Tensorflow-master/data/pretrained_weights/resnet_v1_101.ckpt
********************************************************************************
restore from pretrained_weighs in IMAGE_NET
2018-11-09 15:10:55.101263: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-09 15:10:55.101293: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-09 15:10:55.101309: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-11-09 15:10:55.101314: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-11-09 15:10:55.101320: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2018-11-09 15:10:55.338105: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-11-09 15:10:55.338352: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 960M
major: 5 minor: 0 memoryClockRate (GHz) 1.176
pciBusID 0000:01:00.0
Total memory: 1.96GiB
Free memory: 1.92GiB
2018-11-09 15:10:55.338371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2018-11-09 15:10:55.338382: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2018-11-09 15:10:55.338395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0)
restore model
2018-11-09 15:13:18.442905: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]
......
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]
2018-11-09 15:14:28.174784: W tensorflow/core/framework/op_kernel.cc:1158] Out of range: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    train()
  File "train.py", line 176, in train
    _, global_stepnp, summary_str = sess.run([train_op, global_step, summary_op])
  File "/home/sigma/.virtualenvs/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/sigma/.virtualenvs/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/sigma/.virtualenvs/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/sigma/.virtualenvs/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

Caused by op u'get_batch/batch', defined at:
  File "train.py", line 196, in <module>
    train()
  File "train.py", line 32, in train
    is_training=True)
  File "../data/io/read_tfrecord.py", line 97, in next_batch
    dynamic_pad=True)
  File "/home/sigma/.virtualenvs/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 919, in batch
    name=name)
  File "/home/sigma/.virtualenvs/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 716, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/sigma/.virtualenvs/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/ops/data_flow_ops.py", line 457, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/sigma/.virtualenvs/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 946, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/sigma/.virtualenvs/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/sigma/.virtualenvs/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/sigma/.virtualenvs/tensorflow-gpu/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): PaddingFIFOQueue '_1_get_batch/batch/padding_fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: get_batch/batch = QueueDequeueManyV2[component_types=[DT_STRING, DT_FLOAT, DT_INT32, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](get_batch/batch/padding_fifo_queue, get_batch/batch/n)]]

**Comment by guoguangchao** [comment]
after debug, I found that when read tfrecord file, the 'img_name' , 'img', 'gtboxes_and_label' are normal, the 'img_height','num_objects' always 0, but when convert_data_to_tfrecord , the 'img_height' is right.I have not found the reason.

**Comment by guoguangchao** [comment]
while read tfrecod, I found that the data of features['img_height'] is right, but when run img_height = tf.cast(features['img_height'], tf.int32), img_height turned into 0, I donot know the reason right now.

**Comment by guoguangchao** [comment]
solved this problem after i reinstalled tensorflow.
